ci(workflows): add `release-chore`
- replaces `release-branch`

Signed-off-by: Lexus Drumgold <unicornware@flexdevelopment.llc>

diff --git a/.github/workflows/release-chore.yml b/.github/workflows/release-chore.yml
--- a/.github/workflows/release-chore.yml
+++ b/.github/workflows/release-chore.yml
@@ -1,38 +1,39 @@
-# Release Branch
+# Release Chore
 #
-# Execute version bump, changelog, and pull request operations on release branch creation.
+# Execute branch, version bump, changelog, and pull request operations on release chore commit.
 #
 # References:
 #
-# - https://cli.github.com/manual/gh_auth_status
 # - https://cli.github.com/manual/gh_pr_create
 # - https://docs.github.com/actions/learn-github-actions/contexts
 # - https://docs.github.com/actions/learn-github-actions/expressions
-# - https://docs.github.com/actions/using-workflows/events-that-trigger-workflows#create
+# - https://docs.github.com/actions/using-workflows/events-that-trigger-workflows#push
 # - https://docs.github.com/actions/using-workflows/using-github-cli-in-workflows
 # - https://docs.github.com/actions/using-workflows/workflow-commands-for-github-actions
-# - https://docs.github.com/webhooks-and-events/webhooks/webhook-events-and-payloads#create
+# - https://docs.github.com/webhooks-and-events/webhooks/webhook-events-and-payloads#push
 # - https://github.com/actions/checkout
 # - https://github.com/actions/create-github-app-token
+# - https://github.com/flex-development/gh-commit
 # - https://github.com/hmarr/debug-action
 # - https://github.com/kaisugi/action-regex-match
-# - https://github.com/tohgarashi/verified-commit
 # - https://regex101.com/r/OwpOr2
+# - https://regex101.com/r/VIIVGd
 
 ---
-name: release-branch
-on: create
+name: release-chore
+on:
+  push:
+    branches:
+      - main
 concurrency:
   cancel-in-progress: true
   group: ${{ github.workflow }}-${{ github.ref }}
 jobs:
   preflight:
-    if: |
-      github.ref_type == 'branch' &&
-      startsWith(github.ref_name, 'release/') &&
-      contains(vars.MAINTAINERS, github.actor)
+    if: startsWith(github.event.head_commit.message, 'release(chore):')
     runs-on: ubuntu-latest
     outputs:
+      branch: ${{ steps.branch.outputs.result }}
       message: ${{ steps.message.outputs.result }}
       tag: ${{ steps.tag.outputs.result }}
       version: ${{ steps.version.outputs.match }}
@@ -40,24 +41,46 @@ jobs:
       - id: debug
         name: Print environment variables and event payload
         uses: hmarr/debug-action@v2.1.0
+      - id: fail-actor
+        if: contains(vars.MAINTAINERS, github.actor) == false
+        name: Fail on unauthorized actor
+        run: |
+          echo '**Unauthorized actor: ${{ github.actor }}**' >>$GITHUB_STEP_SUMMARY
+          exit 1
       - id: checkout
         name: Checkout ${{ github.ref_name }}
         uses: actions/checkout@v4.1.1
         with:
           persist-credentials: false
           ref: ${{ github.ref }}
+      - id: diff-tree
+        name: Get diff tree
+        run: echo "result=$(git diff-tree --name-only -r ${{ github.sha }})" >>$GITHUB_OUTPUT
+      - id: fail-diff-tree
+        if: steps.diff-tree.outputs.result != ''
+        name: Fail on invalid diff tree
+        run: |
+          ERR='**Invalid diff tree**
+          ```sh
+          ${{ steps.diff-tree.outputs.result }}
+          ```'
+          echo "$ERR" >>$GITHUB_STEP_SUMMARY
+          exit 1
       - id: version
         name: Get release version
         uses: kaisugi/action-regex-match@v1.0.0
         with:
-          regex: ${{ vars.RELEASE_BRANCH_REGEX }}
-          text: ${{ github.ref_name }}
-      - id: version-fail
+          regex: ${{ vars.RELEASE_CHORE_REGEX }}
+          text: ${{ github.event.head_commit.message }}
+      - id: fail-version
         if: steps.version.outputs.match == ''
         name: Fail on invalid release version
         run: |
-          ERR='**Invalid release branch: ${{ github.ref_name }}**
-          Branch must match [`${{ vars.RELEASE_BRANCH_REGEX }}`](https://regex101.com/r/OwpOr2)'
+          ERR='**Invalid release chore commit**
+          ```sh
+          ${{ github.event.head_commit.message }}
+          ```
+          Message must match [`${{ vars.RELEASE_CHORE_REGEX }}`](https://regex101.com/r/OwpOr2)'
           echo "$ERR" >>$GITHUB_STEP_SUMMARY
           exit 1
       - id: tag
@@ -66,10 +89,35 @@ jobs:
           echo "result=$(jq .tagprefix grease.config.json -r)${{ steps.version.outputs.match }}" >>$GITHUB_OUTPUT
       - id: message
         name: Get release message
-        run: |
-          echo "result=release: ${{ steps.tag.outputs.result }}" >>$GITHUB_OUTPUT
-  prepare:
+        run: 'echo "result=release: ${{ steps.tag.outputs.result }}" >>$GITHUB_OUTPUT'
+      - id: branch
+        name: Get release branch name
+        run: echo "result=release/${{ steps.version.outputs.match }}" >>$GITHUB_OUTPUT
+  branch:
     needs: preflight
+    runs-on: ubuntu-latest
+    steps:
+      - id: bot-token
+        name: Get bot token
+        uses: actions/create-github-app-token@v1.5.1
+        with:
+          app-id: ${{ secrets.BOT_APP_ID }}
+          private-key: ${{ secrets.BOT_PRIVATE_KEY }}
+      - id: checkout
+        name: Checkout ${{ github.ref_name }}
+        uses: actions/checkout@v4.1.1
+        with:
+          ref: ${{ github.ref }}
+          token: ${{ steps.bot-token.outputs.token }}
+      - id: branch
+        name: Create and push branch ${{ needs.preflight.outputs.branch }}
+        run: |
+          git branch ${{ needs.preflight.outputs.branch }}
+          git push origin --no-verify ${{ needs.preflight.outputs.branch }}
+  prepare:
+    needs:
+      - branch
+      - preflight
     permissions:
       packages: read
     runs-on: ubuntu-latest
@@ -83,18 +131,18 @@ jobs:
           app-id: ${{ secrets.BOT_APP_ID }}
           private-key: ${{ secrets.BOT_PRIVATE_KEY }}
       - id: checkout
-        name: Checkout ${{ github.ref_name }}
+        name: Checkout ${{ needs.preflight.outputs.branch }}
         uses: actions/checkout@v4.1.1
         with:
           fetch-depth: 0
           persist-credentials: false
-          ref: ${{ github.ref }}
+          ref: ${{ needs.preflight.outputs.branch }}
           token: ${{ steps.bot-token.outputs.token }}
       - id: yarn
         name: Install dependencies
         env:
           HUSKY: 0
-        run: yarn --immutable
+        run: yarn
       - id: build
         name: Build project
         env:
@@ -111,20 +159,20 @@ jobs:
           echo "$(node ./dist/cli.mjs changelog)" >>$GITHUB_STEP_SUMMARY
           node ./dist/cli.mjs changelog -sw
       - id: commit
-        name: Commit release preparation
-        uses: tohgarashi/verified-commit@v2.1.0
-        env:
-          GH_TOKEN: ${{ steps.bot-token.outputs.token }}
+        name: Commit and push release preparation
+        uses: flex-development/gh-commit@1.0.0
         with:
-          commit-message: |
-            ${{ needs.preflight.outputs.message }}
-
-            Signed-off-by: ${{ vars.BOT_NAME }} <${{ vars.BOT_EMAIL }}>
-
-          detect-changed: true
-          ref: ${{ github.ref }}
+          message: ${{ needs.preflight.outputs.message }}
+          ref: ${{ needs.preflight.outputs.branch }}
+          token: ${{ steps.bot-token.outputs.token }}
+          trailers: 'Signed-off-by: ${{ vars.BOT_NAME }} <${{ vars.BOT_EMAIL }}>'
+      - id: commit-url
+        name: Print commit url
+        run: |
+          echo ${{ format('{0}/{1}/commit/{2}', github.server_url, github.repository, steps.commit.outputs.sha) }}
   pr:
     needs:
+      - branch
       - preflight
       - prepare
     runs-on: ubuntu-latest
@@ -135,21 +183,17 @@ jobs:
         with:
           app-id: ${{ secrets.BOT_APP_ID }}
           private-key: ${{ secrets.BOT_PRIVATE_KEY }}
-      - id: github-token
-        name: Set env.GITHUB_TOKEN
-        run: echo "GITHUB_TOKEN=${{ steps.bot-token.outputs.token }}" >>$GITHUB_ENV
-      - id: gh-auth
-        name: Check gh authentication state
-        run: gh auth status
       - id: checkout
-        name: Checkout ${{ github.ref_name }}
+        name: Checkout ${{ needs.preflight.outputs.branch }}
         uses: actions/checkout@v4.1.1
         with:
           persist-credentials: false
-          ref: ${{ github.ref }}
+          ref: ${{ needs.preflight.outputs.branch }}
           token: ${{ steps.bot-token.outputs.token }}
       - id: pr
         name: Create pull request
+        env:
+          GITHUB_TOKEN: ${{ steps.bot-token.outputs.token }}
         run: |
           gh pr create --title='${{ needs.preflight.outputs.message }}' --label=scope:release --assignee=${{ github.actor }} --reviewer=${{ github.actor }} --body='## Description
 
